### ISSUE TITLE
React template missing .gitignore

### ISSUE THREAD

**Issue by derekgreer** [single-spa/create-single-spa#45] opened 2020-04-01 17:23 UTC
I'm using version 1.3.3 of create-single-spa for the first time.  I chose all the defaults for generating an application, but got an error:

```
AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:\Users\derek.greer\AppData\Roaming\nvm\v13.12.0\node_modules\create-single-spa\node_modules\generator-single-spa\src\react\templates\.gitignore
```

It appears the generator-single-spa-react.js file references a .gitignore file that isn't packaged with the code (see [generator-single-spa-react.js](https://github.com/single-spa/create-single-spa/blob/master/packages/generator-single-spa/src/react/generator-single-spa-react.js#L73)).

**Comment by joeldenning** [comment] 2020-04-01 17:27
This was a duplicate of #41 and was fixed in #42. We had not yet published a new version of create-single-spa since #42 was merged, but I did that just now.

Can you please try out https://github.com/single-spa/create-single-spa/releases/tag/v1.3.4 - that has the fix.

**Closed by joeldenning** 2020-04-01 17:27 UTC
