### ISSUE TITLE
Cannot  load a component library in the application created with create-sigle-spa

### ISSUE THREAD

**Issue by danilorisme** [single-spa/create-single-spa#328] opened 2021-09-08 20:06 UTC
I have a component library made in React and i use Rollup to build the library.

I created a test application using 'create-single-spa' with Typescript.

When I import my component library into the application the following error happens:

`Uncaught Error: application '@org/test' died in status LOADING_SOURCE_CODE: Error loading http://localhost:8500/org-test.js (SystemJS Error#3 https://git.io/JvFET#3) at HTMLScriptElement.<anonymous> (system.js:640)`

![image](https://user-images.githubusercontent.com/5839420/132577989-44f273b8-c70c-4ea6-b4f0-fc180fdb7606.png)

The import test done on the root file:
![image](https://user-images.githubusercontent.com/5839420/132577229-456385eb-ee51-4045-b1af-b6c2b114799e.png)

Testing using an application created with 'create-react-app' the library import normally works.

**Comment by joeldenning** [comment] 2021-09-09 00:32
There's not enough information to diagnose the issue. The link in the error goes to https://github.com/systemjs/systemjs/blob/main/docs/errors.md#3, which explains various causes.

A demonstration of the issue would be best for help diagnosing.

One thing that's unclear is whether the component library is marked as a webpack/rollup external or whether it's published to npm. If it's an external, then it's important what the rollup [`output.format`](https://rollupjs.org/guide/en/#outputformat) is one that is loadable by systemjs (system, amd, or umd). If it's not an external, it should be in esm or cjs format.

There are several steps beyond just the question above to diagnose the issue, but that's as far as I can go without more information.

**Comment by joeldenning** [comment] 2021-09-09 00:38
One specific thing that's missing is the error that likely exists either above or below the area screenshoted in your browser console - that error might say something like SyntaxError or TypeError or a variety of things, but that's the one that would be most helpful for diagnosing. If there is no other error in the browser console, check the network tab to see if the request to download the module is succeeding or not.

**Comment by danilorisme** [comment] 2021-09-09 12:54
@joeldenning 
Thank you for your help!

The component library is in an internal repository for distribution using NPM internally.

There are no other errors in Console or Network.

The only different test I performed and it worked was using the library in an application created using 'create-react-app'.

**Comment by joeldenning** [comment] 2021-09-20 17:45
Since it's not a webpack/rollup external, then the problem is likely just during initial instantiation of the javascript file. One thing to note is that webpack-config-single-spa produces bundles that are in SystemJS format, which is not understood by webpack or rollup when bundling a library. So if you generated the component library project with create-single-spa, then run `npm run build` and publish it to npm, it will not work when bundled with webpack or rollup. That is not what create-single-spa was created for - it instead produces in-browser modules rather than npm packages. However, if you want to do it this way anyway, change the webpack `libraryTarget` to commonjs or module. See https://webpack.js.org/configuration/output/#outputlibrarytarget

**Closed by joeldenning** 2021-09-20 17:45 UTC
