### ISSUE TITLE
 how to use singleSpaDefaults with FederateModule

### ISSUE THREAD

**Issue by jimmyhdolores** [single-spa/create-single-spa#136] opened 2020-06-03 08:36 UTC
I try to use singleSpaDefaults with FederateModule but I get multiple errors, do you have an example?

![image](https://user-images.githubusercontent.com/10909792/83614862-642ca880-a54b-11ea-8644-dd1e15336f2b.png)

**Comment by filoxo** [comment] 2020-06-03 14:55
There is an example of single-spa with Federated Modules here: https://github.com/joeldenning/mfe-webpack-demo/tree/system

We currently do not have plans to integrate federated modules into the starter code that create-single-spa generates so I'm going to close this as it is not a bug or an issue.

**Closed by filoxo** 2020-06-03 14:55 UTC
