### ISSUE TITLE
Cannot get create-single-spa typescript applications to work out-of-box

### ISSUE THREAD

**Issue by aaronkaz** [single-spa/create-single-spa#301] opened 2021-06-29 20:48 UTC
I'm working on a project and cannot get an application compiled with `webpack-config-single-spa-react-ts` to load into a root config app.

I ran `create-single-spa --framework react --moduleType root-config` and created `@testorg/root-config`.

I then ran `create-single-spa --moduleType app-parcel --framework react` and created `@testorg/navbar`.

In both projects I'm using Typescript and in root config, the single-spa Layout Engine.

In `index.ejs` I added `"@testorg/navbar"`
```
<% if (isLocal) { %>
  <script type="systemjs-importmap">
    {
      "imports": {
        "@testorg/root-config": "//localhost:9000/testorg-root-config.js",
        "@testorg/navbar": "//localhost:8500/testorg-navbar.js"
      }
    }
  </script>
  <% } %>
```

In the layout I added:
```
<nav>
    <application name="@testorg/navbar"></application>
  </nav>
```

I get the error:
```Uncaught Error: application '@testorg/navbar' died in status LOADING_SOURCE_CODE: "does not export a bootstrap function or array of functions```

Trying to verify with:
```
System.import('@testorg/navbar').then(application => {
  // Verify that this object has the lifecycle functions on it.
  // If compiling with webpack and consuming in-browser with SystemJS, consider
  // setting webpack's output.libraryTarget to "system".
  console.log(application)
})
```
I get: `Module {Symbol(Symbol.toStringTag): "Module"}`

**Comment by manickam91** [comment] 2021-06-30 09:38
Same here, not sure it is due to the latest version create-single-spa@3.0.0 or single-spa@4.2.0

**Comment by aaronkaz** [comment] 2021-06-30 16:52
I've been trying to pinpoint where the break is...
I pulled in https://github.com/react-microfrontends/root-config and https://github.com/react-microfrontends/navbar to see what's different.  I overrode the `@react-mf/navbar` import to a local version and get the same error:

```
application '@react-mf/navbar' died in status LOADING_SOURCE_CODE: "does not export a bootstrap function or array of functions"
```

This is my first time trying to use single-spa.  I really want it to work...

**Comment by Aaron-Zhao-Asurion** [comment] 2021-06-30 16:54
webpack 5.41.0 and above is not exposing them correctly, downgrade it to 5.40.0 should fix the issue.

I hope the single spa team can dig deeper as to why,

[https://github.com/webpack/webpack/discussions/13651](https://github.com/webpack/webpack/discussions/13651)

**Comment by aaronkaz** [comment] 2021-06-30 17:02
Thanks @Aaron-Zhao-Asurion

**Comment by Vipin-vis** [comment] 2021-07-01 10:47
We have also faced same issue. Everything was fine till last Friday.

To confirm, whether the issue is due to version mismatch or something tried creating a fresh root config app and single spa react app. There also we have faced similar issue.

Thanks @aaronkaz. Downgraded webpack to 5.40.0 and the issue got fixed.

@joeldenning  Please take a look into it.

**Comment by joeldenning** [comment] 2021-07-07 04:00
This is caused by https://github.com/webpack/webpack/issues/13667 which was fixed in https://github.com/webpack/webpack/pull/13689 5 days ago and released in https://github.com/webpack/webpack/releases/tag/v5.42.0

**Closed by joeldenning** 2021-07-07 04:00 UTC
