### ISSUE TITLE
isLocal env variable is not boolean but a string

### ISSUE THREAD

**Issue by JuanRGil** [single-spa/create-single-spa#25] opened 2020-03-09 12:09 UTC
npm init single-spa of type "single-spa root config" generates some scripts in index.ejs file which does not work as expected . This is the code:
`<% if (isLocal) { %>`
When the varibale "isLocal" is set to false (in package.json) the behaviour does not change.
`"start": "webpack-dev-server --mode=development --port 9001 --env.isLocal=false",`
It consider that variable as a string and the result of :
`<% if ("some string including false") { %>`
is true.
It would be great if the script generated in package.json was:
`"start": "webpack-dev-server --mode=development --port 9001 --env.isLocal`
instead of 
`"start": "webpack-dev-server --mode=development --port 9001 --env.isLocal=true",`
As it is confusing.
If we dont want it to be local, we should only remove the argument "--env.isLocal"
`"start": "webpack-dev-server --mode=development --port 9001`

**Comment by joeldenning** [comment] 2020-03-09 23:27
Thanks for the bug report

This is a duplicate of https://github.com/single-spa/create-single-spa/issues/26 and https://github.com/react-microfrontends/root-config/pull/4. It will be fixed by #27 

I'm closing as a duplicate

**Closed by joeldenning** 2020-03-09 23:27 UTC
