### ISSUE TITLE
npx create-single-spa fails when creating a angular application/parcel

### ISSUE THREAD

**Issue by Ecarch** [single-spa/create-single-spa#405] opened 2024-05-08 16:51 UTC
Im trying to create a project for Angular but I always get this error and if I choose another framework it always gives the same error. 

Error: Framework 'svelte' is not yet supported for utility microfrontends. Try creating a vanilla utility module (no framework) in the meantime, which are usable by all frameworks.
    at SingleSpaGenerator.composeChildGenerator (C:\Users\edwar\AppData\Local\npm-cache\_npx\8c5998406a5e5bfb\node_modules\generator-single-spa\src\generator-single-spa.js:152:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.12.0
Angular CLI: 17.3.2

**Comment by dipsx** [comment] 2024-09-10 18:24
Updated to 20.11.1 – it works for m

**Comment by joeldenning** [comment] 2024-09-13 19:54
Closing since the issue is possibly resolved in later versions of Node

**Closed by joeldenning** 2024-09-13 19:54 UTC
