### ISSUE TITLE
vue-router?

### ISSUE THREAD

**Issue by xianglihui** [single-spa/create-single-spa#307] opened 2021-07-14 09:56 UTC
Hello, when I use create single spa framework Vue, why does Vue-router print two consecutive times (console. log), whether in main.ts or router, is this normal?
![page1](https://user-images.githubusercontent.com/84391514/125602925-e77ff77a-c269-425c-acb6-0e1838c6f2c5.png)
![page](https://user-images.githubusercontent.com/84391514/125602943-12e2405e-685b-4dab-91b5-bb05dbaf3b60.png)
[https://github.com/xianglihui/single-spa-App1/tree/master](url)

**Comment by joeldenning** [comment] 2021-07-16 19:36
This is likely caused by the artificial, extraneous popstate event fired by single-spa. See https://single-spa.js.org/docs/api#popstateevent for documentation. I'm closing this as I think that it's probably that. Feel free to comment further or reopen.

**Closed by joeldenning** 2021-07-16 19:36 UTC

**Comment by xianglihui** [comment] 2021-07-17 06:16
Thank you very much for answering my doubts. When I run "serve: standalone" in my project "single-spa-app1", refreshing the page will trigger the "router. Beforeeach" method twice. I don't add any logic to this project for the time being, but simply create the project and add the "router. Beforeeach" method, and finally console. Log. The two triggers make me very confused.
