### ISSUE TITLE
create-single-spa err with Unknown option: '--package-manager'

### ISSUE THREAD

**Issue by Fox-Valentin** [single-spa/create-single-spa#187] opened 2020-09-29 10:14 UTC
hi, here my question and steps:
background:
i use the windows10;
first: 
Install the create-single-spa cli  `npm install --global create-single-spa`;

second：
add the create-single-spa to the enviroment path;

third:
run the script on powershell `create-single-spa`;

forth:
the terminal shows select options and i input as follow:
 Directory for new project (.):   .
Select type to generate: single-spa application / parcel
Which framework do you want to use? angular
Which package manager do you want to use?npm
Project name (can use letters, numbers, dash or underscore): myapp2

fifth:
i tap the enter and the message showed to me:
Unknown option: '--package-manager'
Unknown option: 'npm'

please help with this error message, thanks!

**Comment by filoxo** [comment] 2020-09-29 14:08
Duplicate of #186. One option is to use a current version of @angular/cli.

**Closed by filoxo** 2020-09-29 14:08 UTC

**Comment by filoxo** [comment] 2020-09-30 15:03
This change was published in [create-single-spa@1.14.1](https://github.com/single-spa/create-single-spa/releases/tag/v1.14.1). Please feel free to reopen this issue if the problem persists.
